public class FibonacciMethod {

    /* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
     */

    static int EvenNumSum(int bound) {
        int sum = 0;

        for (int i = 2; i <= bound; i++) {
            int check = fibonacci(i);
            if (check % 2 == 0) {
                sum += check;
            }
        }
        return sum;
    }

    static int fibonacci(int n) {
        if (n == 1 || n == 2) return 1;
        else return fibonacci(n - 1) + fibonacci(n - 2);
    }


}
